name: Application Delivery

on:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Application
        run: mvn clean package
        working-directory: app

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/environments/prod
        run: terraform init -input=false

      - name: Read Outputs
        working-directory: terraform/environments/prod
        run: |
          echo "VM_IP=$(terraform output -raw vm_ip)" >> $GITHUB_ENV
          echo "ACR_NAME=$(terraform output -raw acr_name)" >> $GITHUB_ENV
          echo "ACR_USER=$(terraform output -raw acr_username)" >> $GITHUB_ENV
          echo "ACR_PASS=$(terraform output -raw acr_password | tr -d '\n')" >> $GITHUB_ENV

      - name: Login ACR
        run: |
          echo "${ACR_PASS}" | docker login $ACR_NAME.azurecr.io \
            -u $ACR_USER \
            --password-stdin

      - name: Build Docker Image
        working-directory: app
        run: |
          docker build \
            -t $ACR_NAME.azurecr.io/myapp:${{ github.sha }} \
            -t $ACR_NAME.azurecr.io/myapp:latest \
            .

      - name: Push Image
        run: |
          docker push $ACR_NAME.azurecr.io/myapp:${{ github.sha }}
          docker push $ACR_NAME.azurecr.io/myapp:latest

      - name: Deploy Over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VM_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          envs: ACR_NAME,ACR_USER,ACR_PASS
          script: |
            cd ~/app
            ./deploy.sh

